### PR TITLE
Fix .u and .minimal_components in example notebooks

### PR DESCRIPTION
**Pull request by slel**
For a decomposition `d`, change

- `d.u` to `d.vertical().vertical()`
- `d.minimal_components()` to `d.minimalComponents()`

to reflect recent changes in sage-flatsurf.

##### Dependencies

* [ ] @saraedum failed to make sense of the failing doctests, let's do #72 first to make debugging more reasonable.

### CODE REVIEW

**Comment by slel** [comment]
Not sure why there does not seem to be a need for a similar change
from `undetermined_components` to `undeterminedComponents`.

**Comment by slel** [comment]
The `undeterminedComponents` turned out necessary.
Example notebooks now completely fixed, please review.

**Comment by slel** [comment]
Does this change in `examples/gluings.ipynb` look good to you @saraedum?
```diff
-A = matrix([v0, v1])
+V = O.V2._isomorphic_vector_space
+A = matrix([V(O.V2(v0)), V(O.V2(v1))])
```

And do you understand the doctest failures? Most of them look like one of
```py
AttributeError: 'TranslationSurfaceWidget' object has no attribute '_display_callbacks'
AttributeError: 'FlatTriangulationWidget' object has no attribute '_display_callbacks'
AttributeError: 'FlowDecompositionWidget' object has no attribute '_display_callbacks'
AttributeError: 'FlowComponentWidget' object has no attribute '_display_callbacks'
```

**Comment by saraedum** [comment]
Fixed in #81.

**Pull request closed without merging**
